Repository atmgrupomaggioli/docshub, pull requests merged in 2024-12, with the labels that each got.

#8 ✨ feature/design-improvements
  docshub/src/components/brand/brandTag.astro
  docshub/src/components/brand/docshubBrand.astro
  docshub/src/components/docshubBrand.astro
  docshub/src/components/layout/sidebar/sidebar-collapse.tsx
  docshub/src/components/layout/sidebar/sidebar-content.tsx
  docshub/src/components/layout/sidebar/sidebar.astro
  docshub/src/components/mdx/alert/alert.astro
  docshub/src/components/mdx/alert/alert.types.ts
  docshub/src/components/navbar-top.astro
  docshub/src/components/searchDocs.tsx
  docshub/src/components/ui/alert.astro
  docshub/src/components/ui/command.tsx
  docshub/src/components/ui/dialog.tsx
  docshub/src/docs/mermaid.mdx
  docshub/src/env.d.ts
  docshub/src/layouts/layoutDocs.astro
  docshub/src/pages/[...slug].astro
Labels: enhancement, 🧑‍🚀 next

#9 📚 docs/improvements
  README.md
  docshub/README.md
  docshub/src/docs/docshub-cli.mdx
  docshub/src/docs/docshub-config.mdx
  docshub/src/docs/docshub-docker.mdx
  docshub/src/docs/docshub-source.mdx
  docshub/src/docs/getting-started.mdx
  docshub/src/docs/write.mdx
Labels: 🧑‍🚀 next

#12 ✨ feature/app improvements
  README.md
  docshub/docshub.config.ts
  docshub/public/favicon.svg
  docshub/public/images/README.md
  docshub/public/images/dark_screenshot.png
  docshub/public/images/docker-img.png
  docshub/public/images/docshub.jpg
  docshub/public/images/docshub_cli.png
  docshub/public/images/docshub_transparent.png
  docshub/public/images/light_screenshot.png
  docshub/src/components/brand/docshubBrand.astro
  docshub/src/components/layout/sidebar-toc/sidebar-toc.astro
  docshub/src/components/ui/alert.astro
  docshub/src/docs/docshub-cli.mdx
  docshub/src/docs/docshub-config.mdx
  docshub/src/docs/docshub-faststart.mdx
  docshub/src/docs/ui.mdx
  docshub/src/env.d.ts
  docshub/src/layouts/layoutMain.astro
Labels: 🧑‍🚀 next

#14 ✨ feature/og-image - Add dynamic open graph support
  docshub/astro.config.ts
  docshub/docshub.config.ts
  docshub/package-lock.json
  docshub/package.json
  docshub/src/components/mdx/components.ts
  docshub/src/env.d.ts
  docshub/src/layouts/layoutMain.astro
  docshub/src/og-image/Inter-ExtraBold.ttf
  docshub/src/og-image/InterDisplay-Regular.ttf
  docshub/src/og-image/InterDisplay-SemiBold.ttf
  docshub/src/og-image/documentOg.tsx
  docshub/src/og-image/og-utils.ts
  docshub/src/pages/[...slug].astro
  docshub/src/pages/index.astro
  docshub/src/pages/og/[document].ts
Labels: 🧑‍🚀 next

#15 Feature/multi deploy
  docshub/Dockerfile.interactive
  docshub/Dockerfile.prod
  docshub/README.md
  docshub/astro.config.ts
  docshub/deployment.config.ts
  docshub/docshub.config.ts
  docshub/src/env.d.ts
Labels: 🧑‍🚀 next

#16 Refactor/docs typing & CLI
  cli/src/globals.ts
  cli/src/utils/generate.ts
  docshub/src/components/mdx/components.ts
  docshub/src/docs/docshub-cli.mdx
  docshub/src/docs/docshub-docker.mdx
  docshub/src/docs/env-config.mdx
  docshub/src/docs/env-reference.mdx
  docshub/src/docs/getting-started.mdx
  resources/docker-compose.yml
  resources/env-template
Labels: 🧑‍🚀 next

#17 Feature/ CLI power up + Deploy fixes + Documentation
  cli/package-lock.json
  cli/package.json
  cli/src/core/main.ts
  cli/src/core/manual.ts
  cli/src/core/prompts.ts
  cli/src/globals.ts
  cli/src/index.ts
  cli/src/types/types.ts
  cli/src/utils/ansi.ts
  cli/src/utils/exec.ts
  cli/src/utils/file.ts
  cli/src/utils/fileHelpers.ts
  cli/src/utils/generate.ts
  cli/src/utils/guess.ts
  cli/src/utils/information.ts
  cli/src/utils/resources.ts
  cli/src/utils/validation.ts
  docshub/deployment.config.ts
  docshub/package-lock.json
  docshub/package.json
  docshub/src/components/mdx/components.ts
  docshub/src/docs/docshub-cli.mdx
  docshub/src/docs/docshub-docker.mdx
  docshub/src/docs/docshub-faststart.mdx
  docshub/src/docs/env-config.mdx
  docshub/src/docs/env-reference.mdx
  docshub/src/docs/getting-started.mdx
  docshub/src/docs/write.mdx
Labels: 🧙‍♂️next 2

#18 refactor/ Last Entries Component
  docshub/src/components/last-entries.astro
Labels: 🧙‍♂️next 2
